### ISSUE TITLE
Cannot change SSID/PSK

### ISSUE THREAD

**Issue by sigmapi332** [Splines/raspi-captive-portal#11] opened 2024-08-18 18:58 UTC
Could be that I'm just dumber than I thought (totally plausible), but I cannot get splines to change from the default SSID and PSK. I have modified those fields in the hostapd.conf file in the "access-point" folder and saved it but the network still shows up with the default SSID and requires the default PSK. 

I rebooted the Pi a couple of times to see if that would sort it; it didn't. Verified after reboot that the changes I made in the hostapd.conf file are still there... so at this point I have no idea what I'm missing that isn't putting the changes into effect.

**Comment by Splines** [comment] 2024-08-18 23:39
Hey, once you've modified these values you have to run the script again since it copies those files to the proper locations on your RaspberryPi. From there, other software managing the network is reading the config values. You may also want to try to restart the `hostapd` service (`sudo systemctl restart hostapd`) afterwards.

**Comment by Splines** [comment] 2024-09-05 09:52
I'll close this issue for now, if this is still a problem, you can for sure just open the issue again with a detailed description of the steps to reproduce the problem.

**Closed by Splines** 2024-09-05 09:52 UTC
